//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stub-classes//android/support/v4/util/LruCache.java
//

#ifndef _AndroidSupportV4UtilLruCache_H_
#define _AndroidSupportV4UtilLruCache_H_

#include "J2ObjC_header.h"

@protocol JavaUtilMap;

@interface AndroidSupportV4UtilLruCache : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)maxSize;

- (jint)createCount;

- (void)evictAll;

- (jint)evictionCount;

- (id)getWithId:(id)key;

- (jint)hitCount;

- (jint)maxSize;

- (jint)missCount;

- (id)putWithId:(id)key
         withId:(id)value;

- (jint)putCount;

- (id)removeWithId:(id)key;

- (void)resizeWithInt:(jint)maxSize;

- (jint)size;

- (id<JavaUtilMap>)snapshot;

- (NSString *)description;

- (void)trimToSizeWithInt:(jint)maxSize;

#pragma mark Protected

- (id)createWithId:(id)key;

- (void)entryRemovedWithBoolean:(jboolean)evicted
                         withId:(id)key
                         withId:(id)oldValue
                         withId:(id)newValue;

- (jint)sizeOfWithId:(id)key
              withId:(id)value;

@end

J2OBJC_EMPTY_STATIC_INIT(AndroidSupportV4UtilLruCache)

FOUNDATION_EXPORT void AndroidSupportV4UtilLruCache_initWithInt_(AndroidSupportV4UtilLruCache *self, jint maxSize);

FOUNDATION_EXPORT AndroidSupportV4UtilLruCache *new_AndroidSupportV4UtilLruCache_initWithInt_(jint maxSize) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(AndroidSupportV4UtilLruCache)

#endif // _AndroidSupportV4UtilLruCache_H_
