//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/provider/Images.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsProviderImages_H_
#define _ComExampleAndroidDisplayingbitmapsProviderImages_H_

#include "J2ObjC_header.h"

@class IOSObjectArray;

@interface ComExampleAndroidDisplayingbitmapsProviderImages : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsProviderImages)

FOUNDATION_EXPORT IOSObjectArray *ComExampleAndroidDisplayingbitmapsProviderImages_imageUrls_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsProviderImages, imageUrls_, IOSObjectArray *)

FOUNDATION_EXPORT IOSObjectArray *ComExampleAndroidDisplayingbitmapsProviderImages_imageThumbUrls_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsProviderImages, imageThumbUrls_, IOSObjectArray *)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsProviderImages_init(ComExampleAndroidDisplayingbitmapsProviderImages *self);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsProviderImages *new_ComExampleAndroidDisplayingbitmapsProviderImages_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsProviderImages)

#endif // _ComExampleAndroidDisplayingbitmapsProviderImages_H_
