//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/common/logger/Log.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "android/util/Log.h"
#include "com/example/android/common/logger/Log.h"
#include "com/example/android/common/logger/LogNode.h"
#include "java/lang/Throwable.h"

static id<ComExampleAndroidCommonLoggerLogNode> ComExampleAndroidCommonLoggerLog_mLogNode_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidCommonLoggerLog, mLogNode_, id<ComExampleAndroidCommonLoggerLogNode>)
J2OBJC_STATIC_FIELD_SETTER(ComExampleAndroidCommonLoggerLog, mLogNode_, id<ComExampleAndroidCommonLoggerLogNode>)

@implementation ComExampleAndroidCommonLoggerLog

+ (id<ComExampleAndroidCommonLoggerLogNode>)getLogNode {
  return ComExampleAndroidCommonLoggerLog_getLogNode();
}

+ (void)setLogNodeWithComExampleAndroidCommonLoggerLogNode:(id<ComExampleAndroidCommonLoggerLogNode>)node {
  ComExampleAndroidCommonLoggerLog_setLogNodeWithComExampleAndroidCommonLoggerLogNode_(node);
}

+ (void)printlnWithInt:(jint)priority
          withNSString:(NSString *)tag
          withNSString:(NSString *)msg
 withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(priority, tag, msg, tr);
}

+ (void)printlnWithInt:(jint)priority
          withNSString:(NSString *)tag
          withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_(priority, tag, msg);
}

+ (void)vWithNSString:(NSString *)tag
         withNSString:(NSString *)msg
withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_vWithNSString_withNSString_withJavaLangThrowable_(tag, msg, tr);
}

+ (void)vWithNSString:(NSString *)tag
         withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_vWithNSString_withNSString_(tag, msg);
}

+ (void)dWithNSString:(NSString *)tag
         withNSString:(NSString *)msg
withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_dWithNSString_withNSString_withJavaLangThrowable_(tag, msg, tr);
}

+ (void)dWithNSString:(NSString *)tag
         withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_dWithNSString_withNSString_(tag, msg);
}

+ (void)iWithNSString:(NSString *)tag
         withNSString:(NSString *)msg
withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_iWithNSString_withNSString_withJavaLangThrowable_(tag, msg, tr);
}

+ (void)iWithNSString:(NSString *)tag
         withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_iWithNSString_withNSString_(tag, msg);
}

+ (void)wWithNSString:(NSString *)tag
         withNSString:(NSString *)msg
withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_wWithNSString_withNSString_withJavaLangThrowable_(tag, msg, tr);
}

+ (void)wWithNSString:(NSString *)tag
         withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_wWithNSString_withNSString_(tag, msg);
}

+ (void)wWithNSString:(NSString *)tag
withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_wWithNSString_withJavaLangThrowable_(tag, tr);
}

+ (void)eWithNSString:(NSString *)tag
         withNSString:(NSString *)msg
withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_eWithNSString_withNSString_withJavaLangThrowable_(tag, msg, tr);
}

+ (void)eWithNSString:(NSString *)tag
         withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_eWithNSString_withNSString_(tag, msg);
}

+ (void)wtfWithNSString:(NSString *)tag
           withNSString:(NSString *)msg
  withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_wtfWithNSString_withNSString_withJavaLangThrowable_(tag, msg, tr);
}

+ (void)wtfWithNSString:(NSString *)tag
           withNSString:(NSString *)msg {
  ComExampleAndroidCommonLoggerLog_wtfWithNSString_withNSString_(tag, msg);
}

+ (void)wtfWithNSString:(NSString *)tag
  withJavaLangThrowable:(JavaLangThrowable *)tr {
  ComExampleAndroidCommonLoggerLog_wtfWithNSString_withJavaLangThrowable_(tag, tr);
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComExampleAndroidCommonLoggerLog_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getLogNode", NULL, "Lcom.example.android.common.logger.LogNode;", 0x9, NULL, NULL },
    { "setLogNodeWithComExampleAndroidCommonLoggerLogNode:", "setLogNode", "V", 0x9, NULL, NULL },
    { "printlnWithInt:withNSString:withNSString:withJavaLangThrowable:", "println", "V", 0x9, NULL, NULL },
    { "printlnWithInt:withNSString:withNSString:", "println", "V", 0x9, NULL, NULL },
    { "vWithNSString:withNSString:withJavaLangThrowable:", "v", "V", 0x9, NULL, NULL },
    { "vWithNSString:withNSString:", "v", "V", 0x9, NULL, NULL },
    { "dWithNSString:withNSString:withJavaLangThrowable:", "d", "V", 0x9, NULL, NULL },
    { "dWithNSString:withNSString:", "d", "V", 0x9, NULL, NULL },
    { "iWithNSString:withNSString:withJavaLangThrowable:", "i", "V", 0x9, NULL, NULL },
    { "iWithNSString:withNSString:", "i", "V", 0x9, NULL, NULL },
    { "wWithNSString:withNSString:withJavaLangThrowable:", "w", "V", 0x9, NULL, NULL },
    { "wWithNSString:withNSString:", "w", "V", 0x9, NULL, NULL },
    { "wWithNSString:withJavaLangThrowable:", "w", "V", 0x9, NULL, NULL },
    { "eWithNSString:withNSString:withJavaLangThrowable:", "e", "V", 0x9, NULL, NULL },
    { "eWithNSString:withNSString:", "e", "V", 0x9, NULL, NULL },
    { "wtfWithNSString:withNSString:withJavaLangThrowable:", "wtf", "V", 0x9, NULL, NULL },
    { "wtfWithNSString:withNSString:", "wtf", "V", 0x9, NULL, NULL },
    { "wtfWithNSString:withJavaLangThrowable:", "wtf", "V", 0x9, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NONE", "NONE", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_NONE },
    { "VERBOSE", "VERBOSE", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_VERBOSE },
    { "DEBUG", "DEBUG", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_DEBUG },
    { "INFO", "INFO", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_INFO },
    { "WARN", "WARN", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_WARN },
    { "ERROR", "ERROR", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_ERROR },
    { "ASSERT", "ASSERT", 0x19, "I", NULL, NULL, .constantValue.asInt = ComExampleAndroidCommonLoggerLog_ASSERT },
    { "mLogNode_", NULL, 0xa, "Lcom.example.android.common.logger.LogNode;", &ComExampleAndroidCommonLoggerLog_mLogNode_, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _ComExampleAndroidCommonLoggerLog = { 2, "Log", "com.example.android.common.logger", NULL, 0x1, 19, methods, 8, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidCommonLoggerLog;
}

@end

id<ComExampleAndroidCommonLoggerLogNode> ComExampleAndroidCommonLoggerLog_getLogNode() {
  ComExampleAndroidCommonLoggerLog_initialize();
  return ComExampleAndroidCommonLoggerLog_mLogNode_;
}

void ComExampleAndroidCommonLoggerLog_setLogNodeWithComExampleAndroidCommonLoggerLogNode_(id<ComExampleAndroidCommonLoggerLogNode> node) {
  ComExampleAndroidCommonLoggerLog_initialize();
  JreStrongAssign(&ComExampleAndroidCommonLoggerLog_mLogNode_, node);
}

void ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(jint priority, NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  if (ComExampleAndroidCommonLoggerLog_mLogNode_ != nil) {
    [ComExampleAndroidCommonLoggerLog_mLogNode_ printlnWithInt:priority withNSString:tag withNSString:msg withJavaLangThrowable:tr];
  }
}

void ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_(jint priority, NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(priority, tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_vWithNSString_withNSString_withJavaLangThrowable_(NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(ComExampleAndroidCommonLoggerLog_VERBOSE, tag, msg, tr);
}

void ComExampleAndroidCommonLoggerLog_vWithNSString_withNSString_(NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_vWithNSString_withNSString_withJavaLangThrowable_(tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_dWithNSString_withNSString_withJavaLangThrowable_(NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(ComExampleAndroidCommonLoggerLog_DEBUG, tag, msg, tr);
}

void ComExampleAndroidCommonLoggerLog_dWithNSString_withNSString_(NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_dWithNSString_withNSString_withJavaLangThrowable_(tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_iWithNSString_withNSString_withJavaLangThrowable_(NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(ComExampleAndroidCommonLoggerLog_INFO, tag, msg, tr);
}

void ComExampleAndroidCommonLoggerLog_iWithNSString_withNSString_(NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_iWithNSString_withNSString_withJavaLangThrowable_(tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_wWithNSString_withNSString_withJavaLangThrowable_(NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(ComExampleAndroidCommonLoggerLog_WARN, tag, msg, tr);
}

void ComExampleAndroidCommonLoggerLog_wWithNSString_withNSString_(NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_wWithNSString_withNSString_withJavaLangThrowable_(tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_wWithNSString_withJavaLangThrowable_(NSString *tag, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_wWithNSString_withNSString_withJavaLangThrowable_(tag, nil, tr);
}

void ComExampleAndroidCommonLoggerLog_eWithNSString_withNSString_withJavaLangThrowable_(NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(ComExampleAndroidCommonLoggerLog_ERROR, tag, msg, tr);
}

void ComExampleAndroidCommonLoggerLog_eWithNSString_withNSString_(NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_eWithNSString_withNSString_withJavaLangThrowable_(tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_wtfWithNSString_withNSString_withJavaLangThrowable_(NSString *tag, NSString *msg, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_printlnWithInt_withNSString_withNSString_withJavaLangThrowable_(ComExampleAndroidCommonLoggerLog_ASSERT, tag, msg, tr);
}

void ComExampleAndroidCommonLoggerLog_wtfWithNSString_withNSString_(NSString *tag, NSString *msg) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_wtfWithNSString_withNSString_withJavaLangThrowable_(tag, msg, nil);
}

void ComExampleAndroidCommonLoggerLog_wtfWithNSString_withJavaLangThrowable_(NSString *tag, JavaLangThrowable *tr) {
  ComExampleAndroidCommonLoggerLog_initialize();
  ComExampleAndroidCommonLoggerLog_wtfWithNSString_withNSString_withJavaLangThrowable_(tag, nil, tr);
}

void ComExampleAndroidCommonLoggerLog_init(ComExampleAndroidCommonLoggerLog *self) {
  NSObject_init(self);
}

ComExampleAndroidCommonLoggerLog *new_ComExampleAndroidCommonLoggerLog_init() {
  ComExampleAndroidCommonLoggerLog *self = [ComExampleAndroidCommonLoggerLog alloc];
  ComExampleAndroidCommonLoggerLog_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComExampleAndroidCommonLoggerLog)
