//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/common/logger/LogNode.java
//

#include "J2ObjC_source.h"
#include "com/example/android/common/logger/LogNode.h"
#include "java/lang/Throwable.h"

@interface ComExampleAndroidCommonLoggerLogNode : NSObject

@end

@implementation ComExampleAndroidCommonLoggerLogNode

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "printlnWithInt:withNSString:withNSString:withJavaLangThrowable:", "println", "V", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidCommonLoggerLogNode = { 2, "LogNode", "com.example.android.common.logger", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidCommonLoggerLogNode;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleAndroidCommonLoggerLogNode)
