//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/common/logger/LogNode.java
//

#ifndef _ComExampleAndroidCommonLoggerLogNode_H_
#define _ComExampleAndroidCommonLoggerLogNode_H_

#include "J2ObjC_header.h"

@class JavaLangThrowable;

@protocol ComExampleAndroidCommonLoggerLogNode < NSObject, JavaObject >

- (void)printlnWithInt:(jint)priority
          withNSString:(NSString *)tag
          withNSString:(NSString *)msg
 withJavaLangThrowable:(JavaLangThrowable *)tr;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidCommonLoggerLogNode)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidCommonLoggerLogNode)

#endif // _ComExampleAndroidCommonLoggerLogNode_H_
