//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stub-classes//com/example/android/j2objcdisplayingbitmaps/BuildConfig.java
//

#include "J2ObjC_source.h"
#include "com/example/android/j2objcdisplayingbitmaps/BuildConfig.h"

@implementation ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "DEBUG", "DEBUG", 0x19, "Z", NULL, NULL, .constantValue.asBOOL = ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_DEBUG },
  };
  static const J2ObjcClassInfo _ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig = { 2, "BuildConfig", "com.example.android.j2objcdisplayingbitmaps", NULL, 0x11, 1, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig;
}

@end

void ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_init(ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig *self) {
  NSObject_init(self);
}

ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig *new_ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_init() {
  ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig *self = [ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig alloc];
  ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig)
