//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stub-classes//com/example/android/j2objcdisplayingbitmaps/BuildConfig.java
//

#ifndef _ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_H_
#define _ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_H_

#include "J2ObjC_header.h"

#define ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_DEBUG true

@interface ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig)

J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig, DEBUG, jboolean)

FOUNDATION_EXPORT void ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_init(ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig *self);

FOUNDATION_EXPORT ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig *new_ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig)

#endif // _ComExampleAndroidJ2objcdisplayingbitmapsBuildConfig_H_
