//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractBitmap.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_H_
#define _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

@class ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum;
@class JavaIoOutputStream;

@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap < NSObject, JavaObject >

- (jboolean)compressWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum:(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum *)format
                                                                                        withInt:(jint)quality
                                                                         withJavaIoOutputStream:(JavaIoOutputStream *)stream;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap)

typedef NS_ENUM(NSUInteger, ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormat) {
  ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormat_JPEG = 0,
  ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormat_PNG = 1,
};

@interface ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_values();

+ (ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum *ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum)

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum *ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_values_[];

#define ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_JPEG ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_values_[ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormat_JPEG]
J2OBJC_ENUM_CONSTANT_GETTER(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum, JPEG)

#define ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_PNG ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum_values_[ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormat_PNG]
J2OBJC_ENUM_CONSTANT_GETTER(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum, PNG)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum)

#endif // _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_H_
