//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractBitmapFactory.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_H_
#define _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_H_

#include "J2ObjC_header.h"

@class ComExampleAndroidDisplayingbitmapsUtilImageCache;
@class JavaIoFileDescriptor;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap;

@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory < NSObject, JavaObject >

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)decodeResourceWithInt:(jint)resId;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)decodeSampledBitmapFromResourceWithInt:(jint)resId
                                                                                           withInt:(jint)reqWidth
                                                                                           withInt:(jint)reqHeight
                                              withComExampleAndroidDisplayingbitmapsUtilImageCache:(ComExampleAndroidDisplayingbitmapsUtilImageCache *)cache;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)decodeSampledBitmapFromFileWithNSString:(NSString *)filename
                                                                                            withInt:(jint)reqWidth
                                                                                            withInt:(jint)reqHeight
                                               withComExampleAndroidDisplayingbitmapsUtilImageCache:(ComExampleAndroidDisplayingbitmapsUtilImageCache *)cache;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)decodeSampledBitmapFromDescriptorWithJavaIoFileDescriptor:(JavaIoFileDescriptor *)fileDescriptor
                                                                                                              withInt:(jint)reqWidth
                                                                                                              withInt:(jint)reqHeight
                                                                 withComExampleAndroidDisplayingbitmapsUtilImageCache:(ComExampleAndroidDisplayingbitmapsUtilImageCache *)cache;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory)

#endif // _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_H_
