//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractBitmapFactory.java
//

#include "J2ObjC_source.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmap.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmapFactory.h"
#include "com/example/android/displayingbitmaps/util/ImageCache.h"
#include "java/io/FileDescriptor.h"

@interface ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory : NSObject

@end

@implementation ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "decodeResourceWithInt:", "decodeResource", "Lcom.example.android.displayingbitmaps.util.AbstractBitmap;", 0x401, NULL, NULL },
    { "decodeSampledBitmapFromResourceWithInt:withInt:withInt:withComExampleAndroidDisplayingbitmapsUtilImageCache:", "decodeSampledBitmapFromResource", "Lcom.example.android.displayingbitmaps.util.AbstractBitmap;", 0x401, NULL, NULL },
    { "decodeSampledBitmapFromFileWithNSString:withInt:withInt:withComExampleAndroidDisplayingbitmapsUtilImageCache:", "decodeSampledBitmapFromFile", "Lcom.example.android.displayingbitmaps.util.AbstractBitmap;", 0x401, NULL, NULL },
    { "decodeSampledBitmapFromDescriptorWithJavaIoFileDescriptor:withInt:withInt:withComExampleAndroidDisplayingbitmapsUtilImageCache:", "decodeSampledBitmapFromDescriptor", "Lcom.example.android.displayingbitmaps.util.AbstractBitmap;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory = { 2, "AbstractBitmapFactory", "com.example.android.displayingbitmaps.util", NULL, 0x609, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory)
