//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractBitmapDrawable.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable_H_
#define _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable_H_

#include "J2ObjC_header.h"

@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap;

@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable < NSObject, JavaObject >

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)getBitmap;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable)

#endif // _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable_H_
