//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractBitmapDrawable.java
//

#include "J2ObjC_source.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmap.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmapDrawable.h"

@interface ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable : NSObject

@end

@implementation ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getBitmap", NULL, "Lcom.example.android.displayingbitmaps.util.AbstractBitmap;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable = { 2, "AbstractBitmapDrawable", "com.example.android.displayingbitmaps.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable)
