//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractImageView.java
//

#include "J2ObjC_source.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmap.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmapDrawable.h"
#include "com/example/android/displayingbitmaps/util/AbstractImageView.h"
#include "com/example/android/displayingbitmaps/util/ImageWorker.h"

@interface ComExampleAndroidDisplayingbitmapsUtilAbstractImageView : NSObject

@end

@implementation ComExampleAndroidDisplayingbitmapsUtilAbstractImageView

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "hasOwner", NULL, "Z", 0x401, NULL, NULL },
    { "setImageDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable:", "setImageDrawable", "V", 0x401, NULL, NULL },
    { "setFadeInImageDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmap:withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable:withInt:", "setFadeInImageDrawable", "V", 0x401, NULL, NULL },
    { "setAsyncDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmap:withComExampleAndroidDisplayingbitmapsUtilImageWorker_BitmapWorkerTask:", "setAsyncDrawable", "V", 0x401, NULL, NULL },
    { "getBitmapWorkerTask", NULL, "Lcom.example.android.displayingbitmaps.util.ImageWorker$BitmapWorkerTask;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidDisplayingbitmapsUtilAbstractImageView = { 2, "AbstractImageView", "com.example.android.displayingbitmaps.util", NULL, 0x609, 5, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidDisplayingbitmapsUtilAbstractImageView;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleAndroidDisplayingbitmapsUtilAbstractImageView)
