//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractImageView.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilAbstractImageView_H_
#define _ComExampleAndroidDisplayingbitmapsUtilAbstractImageView_H_

#include "J2ObjC_header.h"

@class ComExampleAndroidDisplayingbitmapsUtilImageWorker_BitmapWorkerTask;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable;

@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractImageView < NSObject, JavaObject >

- (jboolean)hasOwner;

- (void)setImageDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)d;

- (void)setFadeInImageDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmap:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)from
                      withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)to
                                                                               withInt:(jint)durationMillis;

- (void)setAsyncDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmap:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)loadingBitmap
          withComExampleAndroidDisplayingbitmapsUtilImageWorker_BitmapWorkerTask:(ComExampleAndroidDisplayingbitmapsUtilImageWorker_BitmapWorkerTask *)bitmapWorkerTask;

- (ComExampleAndroidDisplayingbitmapsUtilImageWorker_BitmapWorkerTask *)getBitmapWorkerTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAbstractImageView)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAbstractImageView)

#endif // _ComExampleAndroidDisplayingbitmapsUtilAbstractImageView_H_
