//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AbstractBitmapDrawableFactory.java
//

#include "J2ObjC_source.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmap.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmapDrawable.h"
#include "com/example/android/displayingbitmaps/util/AbstractBitmapDrawableFactory.h"

@interface ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory : NSObject

@end

@implementation ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createAbstractBitmapDrawableWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmap:", "createAbstractBitmapDrawable", "Lcom.example.android.displayingbitmaps.util.AbstractBitmapDrawable;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory = { 2, "AbstractBitmapDrawableFactory", "com.example.android.displayingbitmaps.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory)
