//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/AsyncTask.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilAsyncTask_H_
#define _ComExampleAndroidDisplayingbitmapsUtilAsyncTask_H_

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

@class ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum;
@class ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum;
@class IOSObjectArray;
@class JavaUtilConcurrentTimeUnitEnum;
@protocol ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation;
@protocol JavaLangRunnable;
@protocol JavaUtilConcurrentExecutor;

@interface ComExampleAndroidDisplayingbitmapsUtilAsyncTask : NSObject

#pragma mark Public

- (instancetype)initWithComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation:(id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation>)accessor;

- (jboolean)cancelWithBoolean:(jboolean)mayInterruptIfRunning;

- (ComExampleAndroidDisplayingbitmapsUtilAsyncTask *)executeWithNSObjectArray:(IOSObjectArray *)params;

+ (void)executeWithJavaLangRunnable:(id<JavaLangRunnable>)runnable;

- (ComExampleAndroidDisplayingbitmapsUtilAsyncTask *)executeOnExecutorWithJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)exec
                                                                                   withNSObjectArray:(IOSObjectArray *)params;

- (id)get;

- (id)getWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;

- (ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum *)getStatus;

+ (void)init__ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isCancelled;

+ (void)setDefaultExecutorWithJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)exec;

#pragma mark Protected

- (id)doInBackgroundWithNSObjectArray:(IOSObjectArray *)params;

- (void)onCancelled;

- (void)onCancelledWithId:(id)result;

- (void)onPostExecuteWithId:(id)result;

- (void)onPreExecute;

- (void)onProgressUpdateWithNSObjectArray:(IOSObjectArray *)values;

#pragma mark Package-Private

- (void)finishWithId:(id)result;

- (void)publishProgressWithNSObjectArray:(IOSObjectArray *)values;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAsyncTask)

FOUNDATION_EXPORT id<JavaUtilConcurrentExecutor> ComExampleAndroidDisplayingbitmapsUtilAsyncTask_THREAD_POOL_EXECUTOR_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask, THREAD_POOL_EXECUTOR_, id<JavaUtilConcurrentExecutor>)

FOUNDATION_EXPORT id<JavaUtilConcurrentExecutor> ComExampleAndroidDisplayingbitmapsUtilAsyncTask_SERIAL_EXECUTOR_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask, SERIAL_EXECUTOR_, id<JavaUtilConcurrentExecutor>)

FOUNDATION_EXPORT id<JavaUtilConcurrentExecutor> ComExampleAndroidDisplayingbitmapsUtilAsyncTask_DUAL_THREAD_EXECUTOR_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask, DUAL_THREAD_EXECUTOR_, id<JavaUtilConcurrentExecutor>)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilAsyncTask_init__();

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilAsyncTask_setDefaultExecutorWithJavaUtilConcurrentExecutor_(id<JavaUtilConcurrentExecutor> exec);

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilAsyncTask_initWithComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_(ComExampleAndroidDisplayingbitmapsUtilAsyncTask *self, id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation> accessor);

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilAsyncTask_executeWithJavaLangRunnable_(id<JavaLangRunnable> runnable);

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask)

typedef NS_ENUM(NSUInteger, ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status) {
  ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status_PENDING = 0,
  ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status_RUNNING = 1,
  ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status_FINISHED = 2,
};

@interface ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_values();

+ (ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum *ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum)

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum *ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_values_[];

#define ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_PENDING ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_values_[ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status_PENDING]
J2OBJC_ENUM_CONSTANT_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum, PENDING)

#define ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_RUNNING ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_values_[ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status_RUNNING]
J2OBJC_ENUM_CONSTANT_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum, RUNNING)

#define ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_FINISHED ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum_values_[ComExampleAndroidDisplayingbitmapsUtilAsyncTask_Status_FINISHED]
J2OBJC_ENUM_CONSTANT_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum, FINISHED)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_StatusEnum)

@protocol ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation < NSObject, JavaObject >

- (void)setThreadPriorityWithComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum:(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum *)priority;

- (void)publishProgressWithComExampleAndroidDisplayingbitmapsUtilAsyncTask:(ComExampleAndroidDisplayingbitmapsUtilAsyncTask *)task
                                                         withNSObjectArray:(IOSObjectArray *)values;

- (void)postResultWithComExampleAndroidDisplayingbitmapsUtilAsyncTask:(ComExampleAndroidDisplayingbitmapsUtilAsyncTask *)task
                                                               withId:(id)result;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation)

typedef NS_ENUM(NSUInteger, ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_Priority) {
  ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_Priority_THREAD_PRIORITY_BACKGROUND = 0,
};

@interface ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum : JavaLangEnum < NSCopying >

#pragma mark Package-Private

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum_values();

+ (ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum *)valueOfWithNSString:(NSString *)name;
FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum *ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum_valueOfWithNSString_(NSString *name);

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum)

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum *ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum_values_[];

#define ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum_THREAD_PRIORITY_BACKGROUND ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum_values_[ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_Priority_THREAD_PRIORITY_BACKGROUND]
J2OBJC_ENUM_CONSTANT_GETTER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum, THREAD_PRIORITY_BACKGROUND)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_PriorityEnum)

#endif // _ComExampleAndroidDisplayingbitmapsUtilAsyncTask_H_
