//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/DiskLruCache.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_H_
#define _ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_H_

#include "J2ObjC_header.h"
#include "java/io/Closeable.h"

@class ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Editor;
@class ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Snapshot;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaIoReader;

#define ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_ANY_SEQUENCE_NUMBER -1LL

@interface ComExampleAndroidDisplayingbitmapsUtilDiskLruCache : NSObject < JavaIoCloseable >

#pragma mark Public

- (void)close;

+ (void)closeQuietlyWithJavaIoCloseable:(id<JavaIoCloseable>)closeable;

- (void)delete__;

+ (void)deleteContentsWithJavaIoFile:(JavaIoFile *)dir;

- (ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Editor *)editWithNSString:(NSString *)key;

- (void)flush;

- (ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Snapshot *)getWithNSString:(NSString *)key;

- (JavaIoFile *)getDirectory;

- (jboolean)isClosed;

- (jlong)maxSize;

+ (ComExampleAndroidDisplayingbitmapsUtilDiskLruCache *)openWithJavaIoFile:(JavaIoFile *)directory
                                                                   withInt:(jint)appVersion
                                                                   withInt:(jint)valueCount
                                                                  withLong:(jlong)maxSize;

+ (NSString *)readAsciiLineWithJavaIoInputStream:(JavaIoInputStream *)inArg;

+ (NSString *)readFullyWithJavaIoReader:(JavaIoReader *)reader;

- (jboolean)removeWithNSString:(NSString *)key;

- (jlong)size;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache)

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_JOURNAL_FILE_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache, JOURNAL_FILE_, NSString *)

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_JOURNAL_FILE_TMP_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache, JOURNAL_FILE_TMP_, NSString *)

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_MAGIC_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache, MAGIC_, NSString *)

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_VERSION_1_;
J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache, VERSION_1_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache, ANY_SEQUENCE_NUMBER, jlong)

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_readFullyWithJavaIoReader_(JavaIoReader *reader);

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_readAsciiLineWithJavaIoInputStream_(JavaIoInputStream *inArg);

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_closeQuietlyWithJavaIoCloseable_(id<JavaIoCloseable> closeable);

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_deleteContentsWithJavaIoFile_(JavaIoFile *dir);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilDiskLruCache *ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_openWithJavaIoFile_withInt_withInt_withLong_(JavaIoFile *directory, jint appVersion, jint valueCount, jlong maxSize);

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache)

@interface ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Snapshot : NSObject < JavaIoCloseable >

#pragma mark Public

- (void)close;

- (ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Editor *)edit;

- (JavaIoInputStream *)getInputStreamWithInt:(jint)index;

- (NSString *)getStringWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Snapshot)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Snapshot)

@interface ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Editor : NSObject

#pragma mark Public

- (void)abort;

- (void)commit;

- (NSString *)getStringWithInt:(jint)index;

- (JavaIoInputStream *)newInputStreamWithInt:(jint)index OBJC_METHOD_FAMILY_NONE;

- (JavaIoOutputStream *)newOutputStreamWithInt:(jint)index OBJC_METHOD_FAMILY_NONE;

- (void)setWithInt:(jint)index
      withNSString:(NSString *)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Editor)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_Editor)

#endif // _ComExampleAndroidDisplayingbitmapsUtilDiskLruCache_H_
