//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/DiskEnvironment.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_H_
#define _ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_H_

#include "J2ObjC_header.h"

@class JavaIoFile;

@interface ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment : NSObject

#pragma mark Public

- (JavaIoFile *)getDiskCacheDirWithNSString:(NSString *)uniqueName;

- (jlong)getUsableSpaceWithJavaIoFile:(JavaIoFile *)path;

#pragma mark Protected

- (NSString *)getDiskCacheDirPathWithNSString:(NSString *)uniqueName;

- (jlong)getUsableSpaceWithNSString:(NSString *)path;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_init(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *self);

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment)

#endif // _ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_H_
