//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/ImageResizer.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilImageResizer_H_
#define _ComExampleAndroidDisplayingbitmapsUtilImageResizer_H_

#include "J2ObjC_header.h"
#include "com/example/android/displayingbitmaps/util/ImageWorker.h"

@class ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory;
@protocol ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation;
@protocol ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory;

@interface ComExampleAndroidDisplayingbitmapsUtilImageResizer : ComExampleAndroidDisplayingbitmapsUtilImageWorker {
 @public
  jint mImageWidth_;
  jint mImageHeight_;
}

#pragma mark Public

- (instancetype)initWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory>)bitmapFactory
            withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory>)bitmapDrawableFactory
                  withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory:(id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory>)memoryImageCacheFactory
                          withComExampleAndroidDisplayingbitmapsUtilDiskEnvironment:(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *)diskEnvironment
                withComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation:(id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation>)accessor
                                                                            withInt:(jint)imageSize;

- (instancetype)initWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory>)bitmapFactory
            withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory>)bitmapDrawableFactory
                  withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory:(id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory>)memoryImageCacheFactory
                          withComExampleAndroidDisplayingbitmapsUtilDiskEnvironment:(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *)diskEnvironment
                withComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation:(id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation>)accessor
                                                                            withInt:(jint)imageWidth
                                                                            withInt:(jint)imageHeight;

+ (jint)calculateInSampleSizeWithInt:(jint)width
                             withInt:(jint)height
                             withInt:(jint)reqWidth
                             withInt:(jint)reqHeight;

- (void)setImageSizeWithInt:(jint)size;

- (void)setImageSizeWithInt:(jint)width
                    withInt:(jint)height;

#pragma mark Protected

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)processBitmapWithId:(id)data;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilImageResizer)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilImageResizer_initWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory_withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_withComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_withComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_withInt_withInt_(ComExampleAndroidDisplayingbitmapsUtilImageResizer *self, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory> bitmapFactory, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory> bitmapDrawableFactory, id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory> memoryImageCacheFactory, ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *diskEnvironment, id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation> accessor, jint imageWidth, jint imageHeight);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilImageResizer *new_ComExampleAndroidDisplayingbitmapsUtilImageResizer_initWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory_withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_withComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_withComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_withInt_withInt_(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory> bitmapFactory, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory> bitmapDrawableFactory, id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory> memoryImageCacheFactory, ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *diskEnvironment, id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation> accessor, jint imageWidth, jint imageHeight) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilImageResizer_initWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory_withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_withComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_withComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_withInt_(ComExampleAndroidDisplayingbitmapsUtilImageResizer *self, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory> bitmapFactory, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory> bitmapDrawableFactory, id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory> memoryImageCacheFactory, ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *diskEnvironment, id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation> accessor, jint imageSize);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilImageResizer *new_ComExampleAndroidDisplayingbitmapsUtilImageResizer_initWithComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory_withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_withComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_withComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation_withInt_(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory> bitmapFactory, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawableFactory> bitmapDrawableFactory, id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory> memoryImageCacheFactory, ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *diskEnvironment, id<ComExampleAndroidDisplayingbitmapsUtilAsyncTask_ThreadOperation> accessor, jint imageSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT jint ComExampleAndroidDisplayingbitmapsUtilImageResizer_calculateInSampleSizeWithInt_withInt_withInt_withInt_(jint width, jint height, jint reqWidth, jint reqHeight);

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilImageResizer)

#endif // _ComExampleAndroidDisplayingbitmapsUtilImageResizer_H_
