//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/ImageCache.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilImageCache_H_
#define _ComExampleAndroidDisplayingbitmapsUtilImageCache_H_

#include "J2ObjC_header.h"

@class ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum;
@class ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment;
@class ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams;
@class JavaIoFile;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory;
@protocol ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolder;
@protocol ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory;
@protocol ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory;

@interface ComExampleAndroidDisplayingbitmapsUtilImageCache : NSObject

#pragma mark Public

- (void)addBitmapToCacheWithNSString:(NSString *)data
withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)value;

- (void)clearCache;

- (void)close;

- (void)flush;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)getBitmapFromDiskCacheWithNSString:(NSString *)data;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)getBitmapFromMemCacheWithNSString:(NSString *)data;

+ (ComExampleAndroidDisplayingbitmapsUtilImageCache *)getInstanceWithComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory:(id<ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory>)objectHolderFactory
                                                                        withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory:(id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory>)memoryImageCacheFactory
                                                                          withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory>)bitmapFactory
                                                                    withComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams:(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams *)cacheParams;

- (jlong)getUsableSpaceWithJavaIoFile:(JavaIoFile *)path;

+ (NSString *)hashKeyForDiskWithNSString:(NSString *)key;

- (void)initDiskCache OBJC_METHOD_FAMILY_NONE;

#pragma mark Protected

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)getBitmapFromReusableSetWithId:(id)optionsPlatformDepend;

@end

J2OBJC_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilImageCache)

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilImageCache *ComExampleAndroidDisplayingbitmapsUtilImageCache_getInstanceWithComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory_withComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory_withComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams_(id<ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory> objectHolderFactory, id<ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory> memoryImageCacheFactory, id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapFactory> bitmapFactory, ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams *cacheParams);

FOUNDATION_EXPORT NSString *ComExampleAndroidDisplayingbitmapsUtilImageCache_hashKeyForDiskWithNSString_(NSString *key);

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilImageCache)

@interface ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams : NSObject {
 @public
  jint memCacheSize_;
  jint diskCacheSize_;
  JavaIoFile *diskCacheDir_;
  ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum *compressFormat_;
  jint compressQuality_;
  jboolean memoryCacheEnabled_;
  jboolean diskCacheEnabled_;
  jboolean initDiskCacheOnCreate_;
  ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *diskEnvironment_;
}

#pragma mark Public

- (instancetype)initWithComExampleAndroidDisplayingbitmapsUtilDiskEnvironment:(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *)env
                                                                 withNSString:(NSString *)diskCacheDirectoryName;

- (void)setMemCacheSizePercentWithFloat:(jfloat)percent;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams)

J2OBJC_FIELD_SETTER(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams, diskCacheDir_, JavaIoFile *)
J2OBJC_FIELD_SETTER(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams, compressFormat_, ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap_CompressFormatEnum *)
J2OBJC_FIELD_SETTER(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams, diskEnvironment_, ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams_initWithComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_withNSString_(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams *self, ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *env, NSString *diskCacheDirectoryName);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams *new_ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams_initWithComExampleAndroidDisplayingbitmapsUtilDiskEnvironment_withNSString_(ComExampleAndroidDisplayingbitmapsUtilDiskEnvironment *env, NSString *diskCacheDirectoryName) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilImageCache_ImageCacheParams)

@protocol ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory < NSObject, JavaObject >

- (id<ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolder>)getObjectHolderInstance;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolderFactory)

@protocol ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolder < NSObject, JavaObject >

- (id)getObject;

- (void)setObjectWithId:(id)object;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolder)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilImageCache_ObjectHolder)

#endif // _ComExampleAndroidDisplayingbitmapsUtilImageCache_H_
