//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/MemoryImageCacheFactory.java
//

#include "J2ObjC_source.h"
#include "com/example/android/displayingbitmaps/util/MemoryImageCache.h"
#include "com/example/android/displayingbitmaps/util/MemoryImageCacheFactory.h"

@interface ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory : NSObject

@end

@implementation ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createMemoryImageCacheWithInt:", "createMemoryImageCache", "Lcom.example.android.displayingbitmaps.util.MemoryImageCache;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory = { 2, "MemoryImageCacheFactory", "com.example.android.displayingbitmaps.util", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory)
