//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/MemoryImageCache.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_H_
#define _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_H_

#include "J2ObjC_header.h"

@class AndroidSupportV4UtilLruCache;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap;
@protocol ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable;

@interface ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache : NSObject {
 @public
  AndroidSupportV4UtilLruCache *mMemoryCache_;
}

#pragma mark Package-Private

- (instancetype)initWithInt:(jint)maxSize;

- (instancetype)initWithAndroidSupportV4UtilLruCache:(AndroidSupportV4UtilLruCache *)cache;

- (void)evictAll;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)getWithNSString:(NSString *)key;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmap>)getBitmapFromReusableSetWithId:(id)optionsPlatformDepend;

- (id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)putWithNSString:(NSString *)key
                   withComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable:(id<ComExampleAndroidDisplayingbitmapsUtilAbstractBitmapDrawable>)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache)

J2OBJC_FIELD_SETTER(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache, mMemoryCache_, AndroidSupportV4UtilLruCache *)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_initWithAndroidSupportV4UtilLruCache_(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache *self, AndroidSupportV4UtilLruCache *cache);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache *new_ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_initWithAndroidSupportV4UtilLruCache_(AndroidSupportV4UtilLruCache *cache) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_initWithInt_(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache *self, jint maxSize);

FOUNDATION_EXPORT ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache *new_ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_initWithInt_(jint maxSize) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache)

#endif // _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache_H_
