//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/Application/src/shared/java//com/example/android/displayingbitmaps/util/MemoryImageCacheFactory.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_H_
#define _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_H_

#include "J2ObjC_header.h"

@class ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache;

@protocol ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory < NSObject, JavaObject >

- (ComExampleAndroidDisplayingbitmapsUtilMemoryImageCache *)createMemoryImageCacheWithInt:(jint)maxSize;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory)

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory)

#endif // _ComExampleAndroidDisplayingbitmapsUtilMemoryImageCacheFactory_H_
