//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stub-classes//com/example/android/displayingbitmaps/util/Utils.java
//

#ifndef _ComExampleAndroidDisplayingbitmapsUtilUtils_H_
#define _ComExampleAndroidDisplayingbitmapsUtilUtils_H_

#include "J2ObjC_header.h"

@interface ComExampleAndroidDisplayingbitmapsUtilUtils : NSObject

#pragma mark Public

+ (void)enableStrictMode;

+ (jboolean)hasFroyo;

+ (jboolean)hasGingerbread;

+ (jboolean)hasHoneycomb;

+ (jboolean)hasHoneycombMR1;

+ (jboolean)hasJellyBean;

+ (jboolean)hasKitKat;

@end

J2OBJC_EMPTY_STATIC_INIT(ComExampleAndroidDisplayingbitmapsUtilUtils)

FOUNDATION_EXPORT void ComExampleAndroidDisplayingbitmapsUtilUtils_enableStrictMode();

FOUNDATION_EXPORT jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasFroyo();

FOUNDATION_EXPORT jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasGingerbread();

FOUNDATION_EXPORT jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasHoneycomb();

FOUNDATION_EXPORT jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasHoneycombMR1();

FOUNDATION_EXPORT jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasJellyBean();

FOUNDATION_EXPORT jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasKitKat();

J2OBJC_TYPE_LITERAL_HEADER(ComExampleAndroidDisplayingbitmapsUtilUtils)

#endif // _ComExampleAndroidDisplayingbitmapsUtilUtils_H_
