//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: stub-classes//com/example/android/displayingbitmaps/util/Utils.java
//

#include "J2ObjC_source.h"
#include "com/example/android/displayingbitmaps/util/Utils.h"

@interface ComExampleAndroidDisplayingbitmapsUtilUtils ()

- (instancetype)init;

@end

__attribute__((unused)) static void ComExampleAndroidDisplayingbitmapsUtilUtils_init(ComExampleAndroidDisplayingbitmapsUtilUtils *self);

__attribute__((unused)) static ComExampleAndroidDisplayingbitmapsUtilUtils *new_ComExampleAndroidDisplayingbitmapsUtilUtils_init() NS_RETURNS_RETAINED;

@implementation ComExampleAndroidDisplayingbitmapsUtilUtils

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComExampleAndroidDisplayingbitmapsUtilUtils_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)enableStrictMode {
  ComExampleAndroidDisplayingbitmapsUtilUtils_enableStrictMode();
}

+ (jboolean)hasFroyo {
  return ComExampleAndroidDisplayingbitmapsUtilUtils_hasFroyo();
}

+ (jboolean)hasGingerbread {
  return ComExampleAndroidDisplayingbitmapsUtilUtils_hasGingerbread();
}

+ (jboolean)hasHoneycomb {
  return ComExampleAndroidDisplayingbitmapsUtilUtils_hasHoneycomb();
}

+ (jboolean)hasHoneycombMR1 {
  return ComExampleAndroidDisplayingbitmapsUtilUtils_hasHoneycombMR1();
}

+ (jboolean)hasJellyBean {
  return ComExampleAndroidDisplayingbitmapsUtilUtils_hasJellyBean();
}

+ (jboolean)hasKitKat {
  return ComExampleAndroidDisplayingbitmapsUtilUtils_hasKitKat();
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "Utils", NULL, 0x2, NULL, NULL },
    { "enableStrictMode", NULL, "V", 0x9, NULL, NULL },
    { "hasFroyo", NULL, "Z", 0x9, NULL, NULL },
    { "hasGingerbread", NULL, "Z", 0x9, NULL, NULL },
    { "hasHoneycomb", NULL, "Z", 0x9, NULL, NULL },
    { "hasHoneycombMR1", NULL, "Z", 0x9, NULL, NULL },
    { "hasJellyBean", NULL, "Z", 0x9, NULL, NULL },
    { "hasKitKat", NULL, "Z", 0x9, NULL, NULL },
  };
  static const J2ObjcClassInfo _ComExampleAndroidDisplayingbitmapsUtilUtils = { 2, "Utils", "com.example.android.displayingbitmaps.util", NULL, 0x1, 8, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_ComExampleAndroidDisplayingbitmapsUtilUtils;
}

@end

void ComExampleAndroidDisplayingbitmapsUtilUtils_init(ComExampleAndroidDisplayingbitmapsUtilUtils *self) {
  NSObject_init(self);
}

ComExampleAndroidDisplayingbitmapsUtilUtils *new_ComExampleAndroidDisplayingbitmapsUtilUtils_init() {
  ComExampleAndroidDisplayingbitmapsUtilUtils *self = [ComExampleAndroidDisplayingbitmapsUtilUtils alloc];
  ComExampleAndroidDisplayingbitmapsUtilUtils_init(self);
  return self;
}

void ComExampleAndroidDisplayingbitmapsUtilUtils_enableStrictMode() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  ;
}

jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasFroyo() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  return true;
}

jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasGingerbread() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  return true;
}

jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasHoneycomb() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  return true;
}

jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasHoneycombMR1() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  return true;
}

jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasJellyBean() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  return true;
}

jboolean ComExampleAndroidDisplayingbitmapsUtilUtils_hasKitKat() {
  ComExampleAndroidDisplayingbitmapsUtilUtils_initialize();
  return true;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComExampleAndroidDisplayingbitmapsUtilUtils)
